name: Publish samples to NPM

on:
  push:
    tags:
      - 'sample-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: publish sample package
        run: npm install --include peer && npm publish --access=public
        working-directory: plugins/git-proxy-plugin-samples
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
