name: 'Unused Dependencies'
on: [pull_request]

permissions: 
  contents: read 

jobs:
  unused-dependecies:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: '18.x'
      - name: 'Run depcheck'
        run: | 
          npx depcheck --skip-missing --ignores="@babel/*,@commitlint/*,eslint,eslint-*,husky,mocha,concurrently,nyc,prettier"
          echo $?
          if [[ $? == 1 ]]; then
            echo "Unused dependencies or devDependencies found"
            exit 1
          fi

